export const ADD_ORDER_ELEMENT = "ADD_ORDER_ELEMENT";
export const REMOVE_ORDER_ELEMENT = "REMOVE_ORDER_ELEMENT";

//popup
export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";
