//order
export const ADD_PIZZA_ORDER = "ADD_PIZZA_ORDER";
export const REMOVE_PIZZA_ORDER = "REMOVE_PIZZA_ORDER";
export const INCRESE_NUMBER_OF_PIZZA_IN_ORDER =
  "INCRESE_NUMBER_OF_PIZZA_IN_ORDER";
export const DECREASE_NUMBER_OF_PIZZA_IN_ORDER =
  "DECREASE_NUMBER_OF_PIZZA_IN_ORDER";
export const SET_EXTRA_TOPPINGS = "SET_EXTRA_TOPPINGS";
export const SET_SIZE = "SET_SIZE";
//popup
export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";

//pizza
export const REQUEST_PIZZAS = "REQUEST_PIZZAS";
export const RECEIVE_PIZZAS = "RECEIVE_PIZZAS";
export const RECEIVE_PIZZAS_ERROR = "RECEIVE_PIZZAS_ERROR";

//extra Toppings
export const REQUEST_EXTRATOPPINGS = "REQUEST_EXTRATOPPINGS";
export const RECEIVE_EXTRATOPPINGS = "RECEIVE_EXTRATOPPINGS";
export const RECEIVE_EXTRATOPPINGS_ERROR = "RECEIVE_EXTRATOPPINGS_ERROR";

//notification

export const OPEN_NOTIFICATION = "OPEN_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
